# Generated by Django 5.0.7 on 2024-08-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recepies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=500)),
                ('r_decs', models.TextField()),
                ('r_image', models.ImageField(upload_to='recepy')),
            ],
        ),
    ]
