# Generated by Django 5.0.7 on 2024-08-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recepies',
        ),
    ]
