# Generated by Django 5.0.7 on 2024-08-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_delete_recepies'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodct_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_Description', models.TextField()),
                ('product_image', models.ImageField(upload_to='\\images')),
            ],
        ),
    ]
