# Generated by Django 5.0.7 on 2024-08-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['product_type'],
            },
        ),
        migrations.AlterField(
            model_name='product_list',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='product.product_t'),
        ),
    ]
