# Generated by Django 5.0.7 on 2024-08-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_list_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodct_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_Description', models.TextField()),
                ('product_image', models.ImageField(upload_to='images')),
                ('quantity', models.IntegerField()),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='product.product_t')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_F_name', models.CharField(max_length=100)),
                ('customer_L_name', models.CharField(max_length=100)),
                ('customer_mobile_no', models.IntegerField()),
                ('customer_address', models.TextField()),
                ('customer_pincode', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
            ],
            options={
                'unique_together': {('customer_mobile_no', 'customer_email')},
            },
        ),
    ]
