# Generated by Django 5.0.7 on 2024-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_list_product_price_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
