# Generated by Django 5.0.7 on 2024-08-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
