# Generated by Django 5.0.7 on 2024-08-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_customer_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('customer_F_name', models.CharField(max_length=100)),
                ('customer_L_name', models.CharField(max_length=100)),
                ('customer_mobile_no', models.IntegerField()),
                ('customer_address', models.TextField()),
                ('customer_pincode', models.IntegerField()),
                ('customer_gender', models.CharField(default='Male', max_length=10)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'unique_together': {('customer_mobile_no', 'customer_email')},
            },
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
