# Generated by Django 5.0.7 on 2024-08-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_user_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_Description',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='product.user'),
        ),
    ]
