# Generated by Django 5.0.7 on 2024-09-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_cart_prodct_name_remove_cart_product_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='customer',
        ),
    ]
